name: CI Backend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the origin/main branch
on: [push, pull_request]

defaults:
    run:
        working-directory: ./backend

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            neo4j:
                image: neo4j
                ports: -7687:7687
                options: --publish=7474:7474
                    --publish=7687:7687
                env:
                    NEO4JLABS_PLUGINS: ["apoc"]
                    NEO4J_AUTH: none

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm install
            - name: Run lint
              run: npm run lint
            - name: Run tests
              run: npm run test
              env:
                  NEO4J_USERNAME: neo4j
                  NEO4J_PASSWORD: neo4j
