name: CI

on: [push, pull_request]
defaults: 
  run: 
    working-directory: ./webapp

jobs:
  build:
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
